# NinaEssentials plugin is made by Nina.
# Version 0.1.1
# Mininum Minecraft version required: 1.18
# Recommended Minecraft version(s): 1.18.2-LATEST

# DO NOT CHANGE!!!
config-version: 1

serverdetails:
  # {servername} = the servername, check below
  # {ownername} = the ownername, check below
  # {helpers} = the helpers ingame, check below
  # {player} = the player who joins/receives message
  welcome-message: "You joined {servername} that is founded by {ownername}. For questions or inquiries, message these helpers in game: {helpers}. Have fun playing in {servername}, {player}!"
  # sends the server details to the player when they join.
  send-welcome-message: true
  # Server name here, but do not add "smp", "server" or even "the"; e.g. "Graveyard" will return "The Graveyard Server" or "The Graveyard SMP" if smp-mode is enabled.
  name: "MyServer"
  # If true, your servernamae will be "{servername} SMP", otherwise "{servername} Server". This option is NOT affected by `the`.
  smp: true
  # If true, your servername will be "The {servername}", otherwise "{servername}". This option is NOT affected by `smp`.
  the: true
  # Owner name here, must be only one name and no one else. Must be ign name, not discord
  owner-name: "Nina"
  # what people to reach out for when someone has questions, and it must be minecraft name, not discord name.
  helpers: "realguystuff, praneethprogame, and R34per" # Remember to put ", and" because the plugin won't do it for you!
  # link. can be discord link or a website.
  link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  

# logs "<player> has mined <ore>!". disable some of these if the console gets spammed by "<player> has mined <ore>!"
log-mining-ores:
  iron-ore: false
  deepslate-iron-ore: false
  diamond-ore: true
  deepslate-diamond-ore: true
  ancient-debris: true

fixes:
  # When bedrock is destroyed, this plugin will attempt to restore the bedrock immediately.
  fix-bedrock-glitch: true

command-settings:
  setfire:
    enable: true
    fire-ticks: 1200 # 20 ticks = 1 second; 1200 ticks = 1 minute (if server does not lag)
  staffchat:
    enable: true
  randomfact:
    enable: true
  fakeexplosion:
    enable: true
  tntkill:
    enable: true
    explosion-power: 4.0 # DO NOT REMOVE THE DECIMAL!!!!

# use this if you are looking for something wrong or just want to see what this plugin is doing.
verbose: false
# It also logs some information, like if a player attempted to join.
log-logging-in-players: false